### ISSUE TITLE
AT指令怎么发送啊

### ISSUE THREAD

**Issue by poison8** [zhanguangao/react-native-ble-plx-demo#2]
我想给蓝牙模块发送 AT+TEST  这种命令  写入数据哪里写 AT+TEST 显示 不能写入数据  
难道这个模块不能发送AT指令还是我写错了？

**Comment by zhanguangao** [comment]
需要对指令编码后成设备能识别的格式再发送

**Comment by qianlanse** [comment]
和蓝牙连接成功后怎么打印小票呢？可以发送数据，应为主要用安卓，所以我没试只支持ios的react-native-ble-manager-demo，卡在这里了望指点下

**Comment by zhanguangao** [comment]
@qianlanse  一般是先送打印内容，然后再加上指结束指令（例如0x0D, 0x0A，具体看小票打印文档），只发送内容，不加结束指令的话，打印机是不会打印的
