### ISSUE TITLE
打包缺少index.js文件？

### ISSUE THREAD

**Issue by 314863336** [zhanguangao/react-native-ble-plx-demo#5]

**Comment by zhanguangao** [comment]
编译成功了吗？

**Comment by 314863336** [comment]
没成功，感觉你这项目根目录下应该缺失了一个index.js文件，导致打包出错

**Comment by zhanguangao** [comment]
跟文件名没关系，你可以新建项目，然后copy代码过去编译

**Comment by 314863336** [comment]
嗯，谢谢，正在这样做着呢，新生成一个RN项目，然后参考你的代码！

**Comment by 314863336** [comment]
按照你的代码，新生成的项目，略作改动已经可以打包apk运行，但是Genymotion虚拟的安卓机可能因为没有蓝牙硬件，所以无法搜索到蓝牙设备

**Comment by zhanguangao** [comment]
是的，只能用真机调试
